name: ready teh code and deploy

on: [push, workflow_dispatch]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: install node-js
        uses: actions/setup-node@v6
        with:
          node-version: 22.17.0

      - name: copy the code
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm install --frozen-lockfile

      - name: run the linting
        run: npm run lint

  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: install node-js
        uses: actions/setup-node@v6
        with:
          node-version: 22.17.0

      - name: copy the code
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm install --frozen-lockfile

      - name: build the project
        run: npm run build
