name: ready teh code and deploy

on: [push, workflow_dispatch]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: copying the code
        uses: actions/checkout@v4

      - name: install node-js
        uses: actions/setup-node@v6
        with:
          node-version: 22.17.0
      
      - name: check node v
        run: node -v

      - name: install dependencies
        run: npm install --frozen-lockfile

      - name: run the linting
        run: npm run lint