name: ready teh code and deploy

on: [push, workflow_dispatch]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: copying the code
        uses: actions/checkout@v4
      
      - name: check node v
        run: node -v